### PR TITLE
Run/surface wave 2d beach

### PR DESCRIPTION
**Pull request by paulsally**
- Case 1: monochromatic wave with normal incidence – “input_reg.txt”
- Case 2: monochromatic wave with 30-degree incidence – “input_reg_30deg.txt”
- Case 3: irregular waves with peak direction = 0.0 – “input_irr.txt”
- Case 4: irregular waves with peak direction = 30.0 – “input_irr_30deg.txt”

### CODE REVIEW

**Comment by paulsally** [comment]
!!!
the problem is that when I create a pull request GitHub automatically choose the original repo and compares it against it.

**Comment by malej** [comment]
Check your remotes “ got remote”. Your pull/push remotes seem to point to the master branch of the main FUNWAVE repo. Probably want to redirect your remotes to point to your own fork.Then, you will need to sync your fork from time to time with the upstream. git remote show upstreamOn Jul 19, 2024, at 7:30 PM, Sara Polselli ***@***.***> wrote:﻿
!!!
the problem is that when I create a pull request GitHub automatically choose the original repo and compares it against it.

**Comment by paulsally** [comment]
Hi Matt, thanks a lot for your comment!

Actually, git remote -v seems to point correctly to my fork:
```
➜  postprocessing git:(master) git remote -v
origin	https://github.com/paulsally/FUNWAVE-TVD (fetch)
origin	https://github.com/paulsally/FUNWAVE-TVD (push)
```
Yet, when I hit “Create pull request", I get redirected to fengyanshi repo with base branch from the dropdown positioned on the master branch of fengyanshi repo. I need to manually select my repo from the dropdown to be redirected again to my repo. So, if I’m not careful and leave defaults than I end up creating a PR to the wrong repo.
Screenshot 2024-07-20 at 15 31 31
Screenshot 2024-07-20 at 15 32 12
Screenshot 2024-07-20 at 15 32 31

I’m sorry for creating such noise on your repo, I’ll try to pay attention now that I’ve understood Github behaviour on this. I’m used to using BitBucket which doesn’t behave like this and has a differente user interface.

Thanks again.
See you on Monday/Tuesday at the Workshop!

**Comment by malej** [comment]
I see. I always worked off of a command line terminal, so the GUI issue might need to be addressed by someone ***@***.*** - Can you help? You always work off of your forks, right? MattOn Jul 20, 2024, at 9:39 AM, Sara Polselli ***@***.***> wrote:﻿
Hi Matt, thanks a lot for your comment!
Actually, git remote -v seems to point correctly to my fork:
➜  postprocessing git:(master) git remote -v
origin	https://github.com/paulsally/FUNWAVE-TVD (fetch)
origin	https://github.com/paulsally/FUNWAVE-TVD (push)

Yet, when I hit “Create pull request", I get redirected to fengyanshi repo with base branch from the dropdown positioned on the master branch of fengyanshi repo. I need to manually select my repo from the dropdown to be redirected again to my repo. So, if I’m not careful and leave defaults than I end up creating a PR to the wrong repo.
Screenshot.2024-07-20.at.15.31.31.png (view on web)
Screenshot.2024-07-20.at.15.32.12.png (view on web)
Screenshot.2024-07-20.at.15.32.31.png (view on web)
I’m sorry for creating such noise on your repo, I’ll try to pay attention now that I’ve understood Github behaviour on this. I’m used to using BitBucket which doesn’t behave like this and has a differente user interface.
Thanks again.
See you on Monday/Tuesday at the Workshop!

**Comment by paulsally** [comment]
Hi Matt.

I usually create branches and do all operations on them from command line (or VS Code extension) and then move to the GitHub interface to create PRs. 

Looking on the internet it seems that there are quite a few requests on being able to set the base branch other than the upstream but it seems GitHub is not addressing them. [https://github.com/orgs/community/discussions/11729]
Some have created a fork of a fork and archived the middle fork so that PRs against that aren’t possible but I’m not sure how this behaves when it comes to update the working fork.

Some with paying account have opened a ticket with GitHub but for the time being I don’t see a better solution than paying attention.

**Pull request closed without merging**
